# Test the action

name: Test

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # Test a GitHub-hosted runner
  build-Github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
      # Runs this action
      - uses: ./
      # Check that the package was uploaded as an artifact
      - uses: actions/download-artifact@v2
      - name: Check Artifacts
        run: |
          ls -al
          if [ ! -e conda_package ]; then
            echo "conda_package artifact not found"
            exit 1
          fi
          ls -al conda_package

  # Test skipping a build
  skipped-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Deletes the recipe
      - run: rm -rf "conda-recipe"
      # Runs this action, skipping the build but running successfully
      - uses: ./
        with:
          PACKAGE_ARTIFACT_NAME: 'conda_package_skipped'
          TEST_RESULTS_ARTIFACT_NAME: 'test_results_skipped'
      # Check that the package was not uploaded as an artifact
      - uses: actions/download-artifact@v2
      - name: Check Artifacts
        run: |
          ls -al
          if [ -e conda_package ]; then
            ls -al conda_package
            echo "conda_package artifact was found even though it was not supposed to be created."
            exit 1
          fi

  # Test customized build.yml file
  customized-yml:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs this action, skipping the build but running successfully
      - uses: ./
        with:
          CONDA_BUILD_ENV_FILEPATH: 'test_env/test_build.yml'
          TEST_RESULTS_ARTIFACT_NAME: 'customized_test_results'
          PACKAGE_ARTIFACT_NAME: 'conda_package_customized_build'
      - uses: actions/download-artifact@v2
      - name: Check Artifacts
        run: |
          ls -al
          if [ ! -e conda_package_customized_build ]; then
            echo "conda_package artifact not found"
            exit 1
          fi
          ls -al conda_package_customized_build